<?php
                /*NEWS 1.0.0*/
                'id_news_16_0_0' => array(
                    'key' => 'id_news_16_0_0',
                    'name' => 'news_16_0_0',
                    'label' => 'news 1.0.0',
                    'display' => 'block',
                    'sub_fields' => array(
                        /*Bắt đầu field*/
                        array(
                            /* Tab 1*/
                            'key' => 'id_news_16_0_0_tab1',
                            'label' => 'Hoạt Động',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'id_news_16_0_0_tab1_sub1',
                            'label' => 'Tiêu đề',
                            'name' => 'news_title1',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'id_news_16_0_0_tab1_sub2',
                            'label' => 'Danh sách tin',
                            'name' => 'content1',
                            'type' => 'relationship',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => '',
                            'taxonomy' => '',
                            'filters' => array(
                                0 => 'search',
                                1 => 'post_type',
                                2 => 'taxonomy',
                            ),
                            'elements' => array(
                                0 => 'featured_image',
                            ),
                            'min' => '',
                            'max' => '',
                            'return_format' => 'id',
                        ),
                        array(
                            /* Tab 2*/
                            'key' => 'id_news_16_0_0_tab2',
                            'label' => 'Hỏi Đáp',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'id_news_16_0_0_tab2_sub1',
                            'label' => 'Tiêu đề',
                            'name' => 'news_title2',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'id_news_16_0_0_tab2_sub3',
                            'label' => 'Danh sách tin',
                            'name' => 'content2',
                            'type' => 'relationship',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => '',
                            'taxonomy' => '',
                            'filters' => array(
                                0 => 'search',
                                1 => 'post_type',
                                2 => 'taxonomy',
                            ),
                            'elements' => array(
                                0 => 'featured_image',
                            ),
                            'min' => '',
                            'max' => '',
                            'return_format' => 'id',
                        ),
                        array(
                            /* Tab 3*/
                            'key' => 'id_news_16_0_0_tab3',
                            'label' => 'Video Clips',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'id_news_16_0_0_tab3_sub1',
                            'label' => 'Tiêu đề',
                            'name' => 'news_title3',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'id_news_16_0_0_tab3_sub2',
                            'label' => 'Video Clip',
                            'name' => 'news_clips',
                            'type' => 'gallery',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'insert' => 'append',
                            'library' => 'all',
                            'min' => '',
                            'max' => 2,
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                     
                     
                     
                        
                        /*End field*/
                    ),
                    'min' => '',
                    'max' => '',
                ),
                /*END NEWS 1.0.0*/
?>